name: Generate .apk file

on:
  pull_request:
    branches:
      - develop

jobs:
  setup-env:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Use Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
          cache: "yarn"

      - name: Install Node modules
        run: yarn install --frozen-lockfile

  build-android:
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check folder exist
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "node_modules/expo/scripts/"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: echo "node_modules/expo/scripts/ not exist"

      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew assembleRelease --no-daemon && cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
